Stop script when xrdcp fails 10 times

diff --git a/GRIDPACKtoAOD/condor/condor_signal-production b/GRIDPACKtoAOD/condor/condor_signal-production
--- a/GRIDPACKtoAOD/condor/condor_signal-production
+++ b/GRIDPACKtoAOD/condor/condor_signal-production
@@ -103,9 +103,15 @@ for rootfile in evts_8aod.root; do
     echo Copy rootfile "${rootfile}".
     # Since copying to eos often fails for no obvious reason, brute force the copy
     for i in {1..10}; do
-        xrdcp -fs "${rootfile}" root://cmseos.fnal.gov/"${eosoutdir}" \
-            && break \
-            || echo xrdcp try "${i}" for file "${rootfile}" failed.
+        if xrdcp -fs "${rootfile}" root://cmseos.fnal.gov/"${eosoutdir}"; then
+            break
+        else
+            echo "xrdcp try ${i} for file ${rootfile} failed."
+            if [ "${i}" -eq 10 ]; then
+                echo "Give up."
+                exit 2
+            fi
+        fi
     done
 done
 
