Return larger value from either config or cmsRun

diff --git a/LHEtoAOD/CMSSW_7_1_20_patch3/src/cmsDriver_hadronization b/LHEtoAOD/CMSSW_7_1_20_patch3/src/cmsDriver_hadronization
--- a/LHEtoAOD/CMSSW_7_1_20_patch3/src/cmsDriver_hadronization
+++ b/LHEtoAOD/CMSSW_7_1_20_patch3/src/cmsDriver_hadronization
@@ -23,7 +23,7 @@ cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/Hadronizer_TuneCUETP
     --number="${nEvents}" \
     --no_exec
 
-echo "Return value from ${step} config: $?"
+return_value_config="$?"
 
 echo -n "Adding analysis specific lines... "
 
@@ -47,4 +47,13 @@ echo "Done."
 
 cmsRun hadronizer_cfg.py
 
-echo "Return value from ${step} cmsRun: $?"
+return_value_cmsRun="$?"
+echo "Return value from ${step} config: ${return_value_config}"
+echo "Return value from ${step} cmsRun: ${return_value_cmsRun}"
+
+# Return larger return value
+if [ "${return_value_config}" -ge "${return_value_cmsRun}" ]; then
+    return "${return_value_config}"
+else
+    return "${return_value_cmsRun}"
+fi
diff --git a/LHEtoAOD/CMSSW_8_0_3_patch2/src/cmsDriver_digitization b/LHEtoAOD/CMSSW_8_0_3_patch2/src/cmsDriver_digitization
--- a/LHEtoAOD/CMSSW_8_0_3_patch2/src/cmsDriver_digitization
+++ b/LHEtoAOD/CMSSW_8_0_3_patch2/src/cmsDriver_digitization
@@ -19,8 +19,17 @@ cmsDriver.py step1 \
     --number=-1 \
     --no_exec
 
-echo "Return value from ${step} config: $?"
+return_value_config="$?"
 
 cmsRun digitization_cfg.py
 
-echo "Return value from ${step} cmsRun: $?"
+return_value_cmsRun="$?"
+echo "Return value from ${step} config: ${return_value_config}"
+echo "Return value from ${step} cmsRun: ${return_value_cmsRun}"
+
+# Return larger return value
+if [ "${return_value_config}" -ge "${return_value_cmsRun}" ]; then
+    return "${return_value_config}"
+else
+    return "${return_value_cmsRun}"
+fi
